### ISSUE TITLE
use multistage docker build

### ISSUE THREAD

**Issue by savek-cc** [michelde/knxd-docker#1]
Hi!

I just forked your repo to reduce the image size (and use my own knx.ini).
When using a multistage docker build, you can reduce the image size from ~400 to ~40MB (reduce by a factor of 10).
See dockerfile at https://github.com/savek-cc/knxd-docker :)

BR,
Savek

**Comment by michelde** [comment]
Thanks for adjusting the build file. Have adjusted it as well.
